<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Advancednewsletter
 * @version    2.5.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php /* ?>
<?php $this->setBlockUniqueId($this->getBlockUniqueId() + 1) ?>
<?php if (preg_match('/^1.3/', Mage::getVersion())): ?>
<div class="box base-mini mini-newsletter an-subscribe" id="advancednewsletter-subscribe-<?php echo $this->getBlockUniqueId() ?>">
    <form action="<?php echo $this->getUrl('advancednewsletter/index/subscribe', array('_secure'=>Mage::app()->getStore(true)->isCurrentlySecure())) ?>" method="post" id="advancednewsletter-form-<?php echo $this->getBlockUniqueId() ?>">
        <div class="head"><h4><?php echo $this->__('Newsletter') ?></h4></div>
        <div class="block-content">
            <div class="an-segments">
                <?php echo $this->getChildHtml('advancednewsletter.options.'.Mage::getStoreConfig(AW_Advancednewsletter_Block_Subscribe::STYLES_PATH)); ?>
            </div>
            <div>
                <?php echo $this->getChildHtml('advancednewsletter.subscriber.data') ?>
            </div>
            <div class="an-buttons">
                <button type="submit" class="form-button-alt" onclick="advancednewsletterForm<?php echo $this->getBlockUniqueId() ?>.submit()"><span><?php echo $this->__('Subscribe') ?></span></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var advancednewsletterForm<?php echo $this->getBlockUniqueId() ?> = new VarienForm('advancednewsletter-form-<?php echo $this->getBlockUniqueId() ?>');
        //]]>
    </script>
</div>
<?php else: ?>
<div class="block an-subscribe" id="advancednewsletter-subscribe-<?php echo $this->getBlockUniqueId() ?>">
    <form action="<?php echo $this->getUrl('advancednewsletter/index/subscribe', array('_secure'=>Mage::app()->getStore(true)->isCurrentlySecure())) ?>" method="post" id="advancednewsletter-form-<?php echo $this->getBlockUniqueId() ?>">
        <div class="block-title"><strong><span><?php echo $this->__('Newsletter') ?></span></strong></div>
        <div class="block-content">
            <div class="an-segments">
                <?php echo $this->getChildHtml('advancednewsletter.options.'.Mage::getStoreConfig(AW_Advancednewsletter_Block_Subscribe::STYLES_PATH)); ?>
            </div>
            <div>
                <?php echo $this->getChildHtml('advancednewsletter.subscriber.data') ?>
            </div>
            <div class="an-buttons">
                <button type="submit" class="button" onclick="advancednewsletterForm<?php echo $this->getBlockUniqueId() ?>.submit()"><span><?php echo $this->__('Subscribe') ?></span></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var advancednewsletterForm<?php echo $this->getBlockUniqueId() ?> = new VarienForm('advancednewsletter-form-<?php echo $this->getBlockUniqueId() ?>');
        //]]>
    </script>
</div>
<?php endif; ?>
<?php */ ?>

<div id="advancednewsletter_custom">
  <div class="info-container">
     <div class="container">
        <div class="row">
           <div class="col-xs-12">
              <div class="info_block">
                 <div class="index_info_block">
                    <div class="info_col inf1">
                       <div class="inf_icon"></div>
                       <h2><a href="tel:+33 (0)1 83 62 09 66" style="color: white;">+33 (0)1 83 62 09 66</a></h2>
                       <p>Une question ? Appelez-nous.</p>
                       <p>Nous répondons du lundi</p>
                       <p>au vendredi de 9h à 18h.</p>
                    </div>
                    <div class="info_col inf2">
                       <div class="inf_icon"></div>
                       <h2>Paiement sécurisé</h2>
                       <img alt="moyens-de-paiement" class="lazyload" src="https://www.metropole-equipements.com/media/wysiwyg/moye-de-paiement.1568706407.png" style="display: inline-block;">
                    </div>
                    <div class="info_col inf3">
                       <div class="inf_icon"></div>
                       <h2>Livraison</h2>
                       <p>Offerte pour toute commande</p>
                       <p>de plus de 400,00 € <sup>HT </sup></p>
                       <p>en France continentale hors Corse.</p>
                    </div>
                 </div>
              </div>
           </div>
        </div>
     </div>
  </div>

  <div class="newsletter-container">
     <div class="container">
        <div class="row">
           <div class="col-xs-12">
              <div class="newsletter_block">
                 <div class="footer_newsletter">
                    <h2>Newsletter</h2>
                    <form action="<?php echo $this->getUrl('advancednewsletter/index/subscribe', array('_secure'=>Mage::app()->getStore(true)->isCurrentlySecure())) ?>" method="post" id="advancednewsletter-form-<?php echo $this->getBlockUniqueId() ?>">
                       <div class="newsletter-wrapper">
                          <div class="input-box">
                             <input type="text" name="email" id="newsletter" placeholder="E-mail" title="Enter your e-mail" class="input-text required-entry validate-email form-control">
                              <div class="an-segments" style="display: none;">
                                  <?php echo $this->getChildHtml('advancednewsletter.options.'.Mage::getStoreConfig(AW_Advancednewsletter_Block_Subscribe::STYLES_PATH)); ?>
                              </div>
                              <div style="display: none;">
                                  <?php echo $this->getChildHtml('advancednewsletter.subscriber.data') ?>
                              </div>                           
                          </div>
                          <div class="actions">
                             <div>
                                <div class="grecaptcha-badge" data-style="bottomright" style="width: 256px; height: 60px; display: block; transition: right 0.3s ease 0s; position: fixed; bottom: 14px; right: -186px; box-shadow: gray 0px 0px 5px; border-radius: 2px; overflow: hidden;">
                                   <div class="grecaptcha-logo"><iframe src="https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LevjH4UAAAAACsqJs_kRwD4XRRzVAQHMQCJNPg8&amp;co=aHR0cHM6Ly93d3cubWV0cm9wb2xlLWVxdWlwZW1lbnRzLmNvbTo0NDM.&amp;hl=fr&amp;v=bfvuz6tShG5aoZp4K4zPVf5t&amp;size=invisible&amp;cb=g3wvdxxg2ps" width="256" height="60" role="presentation" name="a-n48zfuyn89ji" frameborder="0" scrolling="no" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox"></iframe></div>
                                   <div class="grecaptcha-error"></div>
                                   <textarea id="g-recaptcha-response" name="g-recaptcha-response" class="g-recaptcha-response" style="width: 250px; height: 40px; border: 1px solid rgb(193, 193, 193); margin: 10px 25px; padding: 0px; resize: none; display: none;"></textarea>
                                </div>
                                <iframe style="display: none;"></iframe>
                             </div>
                             <button type="submit" title="Envoyer" class="button advancednewsletter_btn g-recaptcha" data-sitekey="6LevjH4UAAAAACsqJs_kRwD4XRRzVAQHMQCJNPg8"><span><span>Envoyer</span></span></button>
                          </div>
                       </div>
                    </form>
                    <p class="additionnal-text">Ne manquez rien de toutes nos actualités ! Abonnez‑vous !</p>
                 </div>
                 <div style="width: 100%; margin: 0 auto;display: none;" class="nw_msg_err">
                   <p style="color: red; text-align: center;">Veuillez renseigner en email svp.</p>
                 </div>
              </div>
           </div>
        </div>
     </div>
  </div>
</div>

<script type="text/javascript">
  
  jQuery(document).ready(function () {

    var ac = jQuery('#advancednewsletter_custom').html();
    jQuery('.footer-container').before(ac);
    jQuery('#advancednewsletter_custom').html('');

    jQuery('.advancednewsletter_btn').click(function(e) {
      e.preventDefault();

      if ( jQuery('#newsletter').val() == "" ) {
        jQuery('.nw_msg_err').show();
        return false;
      }

      if ( IsEmail(jQuery('#newsletter').val()) == false ) {
        jQuery('.nw_msg_err').show();
        return false;
      }

      jQuery('.nw_msg_err').hide();
      jQuery('#email_an').val(jQuery('#newsletter').val());
      jQuery('#firstname_an').val('-');
      jQuery('#last_name').val('-');
      jQuery('#phone_an').val('-');

      jQuery('#advancednewsletter-form-0').submit();

    });

  });

function IsEmail(email) {
  var regex = /^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
  if(!regex.test(email)) {
    return false;
  }else{
    return true;
  }
}  


</script>